default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || "messenger_bot_development" %>
  username: <%= ENV['DB_USER'] || "trevlig" %>
  password: <%= ENV['DB_PASSWORD'] || "trevlig123" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>
  port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || "messenger_bot_test" %>
  username: <%= ENV['DB_USER'] || "trevlig" %>
  password: <%= ENV['DB_PASSWORD'] || "trevlig123" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>
  port: <%= ENV['DB_PORT'] || 5432 %>

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
